config/routes.rb
Rails.application.routes.draw do


get'tasks', to: "tasks#index"

get'task/:id', to: "tasks#show", as: "created_task"

get 'tasks/new', to:"tasks#new"

post 'tasks', to:"tasks#create"

get 'tasks/:id/edit', to: "tasks#edit", as: "updated_task"

patch 'tasks/:id', to: "tasks#update"

delete 'tasks/:id', to: "tasks#delete", as:"deleted_task"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save

    redirect_to created_task_path(@task.id)
  end

  def edit
     @task = Task.find(params[:id])
  end

  def update
      @task = Task.find(params[:id])
      @task.update(params[:task])

      redirect_to updated_task_path(@task.id)

  end

  def delete
     @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path

  end

private

  def task_params
    params.require(:task).permit(:name, :done)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/delete.html.erb
<h1>Tasks#delete</h1>
<p>Find me in app/views/tasks/delete.html.erb</p>

app/views/tasks/edit.html.erb
<h1>Tasks#edit</h1>

<%= form_for @task do |f| %>
  <%= f.text_field :name , placeholder: "Your task"%>
  <%=f.label :done %>
  <%= f.check_box  :done %>
  <%= f.submit "Update" %>
<% end %>

app/views/tasks/index.html.erb
<h1> All your tasks</h1>

<% @tasks.each do |task| %>
  <h2><%= task.name %></h2>
  <p><%= task.done %></p>

<%= link_to "Delete", deleted_task_path(task),
      method: :delete,
      data: { confirm: "Are you sure?"}%>

<%= link_to "Update", updated_task_path(task) %>

<% end %>

<%= link_to "Create Task", tasks_new_path%>

app/views/tasks/new.html.erb
<%= form_for @task do |f| %>
  <%= f.text_field :name , placeholder: "Your task"%>
  <%=f.label :done %>
  <%= f.check_box  :done %>
  <%= f.submit "Create" %>
<% end %>

app/views/tasks/show.html.erb
<h1>Blablabla</h1>
<h2><%= @task.name%> </h2>